### ISSUE TITLE
[embedded futures] AngularActor doesn't do plumbing.inject on model change

### ISSUE THREAD

**Issue by arkadius** [joescii/lift-ng#10]
Hi,

First of all I would like to thank you for a good piece of work building excellent bridge between lift and Angular.

I've tried to create sample app using embedded futures and stacked on javascript error while updating state of SimpleNgModelBinder by other actor that binder is listener of. As I investigated the problem is that updated model is sended without plumbing. This happens in TwoWaySessionNamed.fromServer - buildMutator only bind new value to scope without plumbing.

I just have been starting advanture with Lift and Lift-ng so its hard for me to propose how to fix this problem but I requested test modification that reproduce the problem: https://github.com/joescii/lift-ng/pull/9.

BTW. during this test, without my modifications, TypeError was thrown in $watch handler, because handler is invoked on initial state which is undefined. I've tried to add some additional webDriver.manage().logs() check on tests ends but this error log haven't been seened by webdriver :-/

Cheers,
Arek

**Comment by joescii** [comment]
Sorry it took me so long to wrap this one up. It turned out to be pretty easy. :+1: Released in 0.7.0
