### ISSUE TITLE
getting "invalid json" when using Long parameter type and not String

### ISSUE THREAD

**Issue by alexmnyc** [joescii/lift-ng#12]
.jsonCall("getPonyByName", (id:Long) => {
      // Return the matching pony
      Full(MyPony.findById(id))
}

**Comment by joescii** [comment]
I'll take a look at this when I get some time.  It's possible that this is a general Lift question, so you may want to post this question on the [Google Group](https://groups.google.com/forum/?hl=en#!forum/liftweb).

**Comment by joescii** [comment]
Sorry I've been slow getting back to you.  As I sit to take a second look at this, probably what should happen is a compilation failure in this case.  The value arguments are `Unit`, `String`, and `NgModel`.  If you want to pass a `Long`, I would recommend defining a simple case class to wrap it up =>

```scala
case class PonyRequest(id:Long) extends NgModel

.jsonCall("getPonyById", (req:PonyRequest) => {
  Full(MyPony.findById(req.id))
}
```

**Comment by joescii** [comment]
I've finally found time to dig into this. I have no idea why this compiles, so I have opened a [stackoverflow question](http://stackoverflow.com/questions/31907701/why-does-this-scala-function-compile-when-the-argument-does-not-conform-to-the-t) to get some insight.

**Comment by joescii** [comment]
This will fail to compile in 0.7.0.
