### ISSUE TITLE
How do you configure angularjs webjar in your classpath?

### ISSUE THREAD

**Issue by odwrotnie** [joescii/lift-ng#13]
When I package the project to `fat JAR` I get this error:

```
The justification for allowing the openOrThrowException was lift-ng has been initialized with includeAngularJs==true but it appears you do not have the angularjs webjar configured in your classpath
```

The error does not occure when I use `sbt run` or package it to `WAR`.

**Comment by joescii** [comment]
How are you building the jar?  I use `sbt-assembly` because it will include all of the dependency jars much like a war file.

**Comment by odwrotnie** [comment]
I am using the same (`sbt-assembly` with default configuration).
This is the `build.scala`: http://pastebin.com/SQcfqZS6
The `main class`: http://pastebin.com/2fR5RV3z

**Comment by joescii** [comment]
Can you add an `echo` of the classpath in the runner script to make sure the webjar is included?

**Comment by odwrotnie** [comment]
I have unzipped both, the JAR does not have `org.webjars.bower`.

**Comment by joescii** [comment]
Ah, I figured it out.  [This](https://github.com/sbt/sbt-assembly/blob/2fb7b2abfe81f98e64eca7ffa471ef9fe63e18a2/src/main/scala/sbtassembly/MergeStrategy.scala#L142-L143) is your problem.  You'll need to define a custom `MergeStrategy`. The [Merge Strategy](https://github.com/sbt/sbt-assembly#merge-strategy) documentation on github shows precisely how you can accomplish this.

**Comment by odwrotnie** [comment]
Thank you!
