### ISSUE TITLE
Lift 3.0-RC2 - JSON Issues

### ISSUE THREAD

**Issue by davenatx** [joescii/lift-ng#15]
It appears there are some lift-json changes in Lift 3 that are causing a few problems in lift-ng.  

First, using Lift 3.0-RC2, when I tried to use `jsconCall`, I received this exception:  `java.lang.NoSuchMethodError: net.liftweb.json.JsonAST$JValue.$bslash$bslash(Ljava/lang/String;)Lnet/liftweb/json/JsonAST$Jvalue;`  I forked lift-ng, bumped the version of Lift to 3.0-RC2 and publishing local.  This did resolved this issue for me.  So, I suspect the version of lift-ng published for Lift 3 was using an older version of Lift 3.

Now, when I use `jsonCall`, I no longer receive the exception.  However, I always receive this message:  `Received invalid JSON from the client…`  After doing a little digging, in the updated version of lift-json,  `json.\\(“data”)` no longer returns the children of data.  However, `json.\(“data”)` does.  I made this change in my local branch of lift-ng and it resolved my issue:  https://github.com/davenatx/lift-ng/commit/a5373b883c24f5cc98a8bff9f0dcff2bdef4392c

For what it is worth, I did start a discussion about this on the Lift mailing list and Antonio did confirm the lift-json changes in Lift 3:  https://groups.google.com/forum/#!topic/liftweb/xTR297UXjyo

Please let me know if there is anything I can do to help resolve this.

**Comment by joescii** [comment]
Thanks for investigating that issue! From time to time, plugins built for Lift 3 hit those problems because of breaking changes to the compiled code. The lift-json change is a bit tricky because I'll have to fix it up to compile with the old code in 2.x and the new in 3.x. I know how to do it, though.

Thanks!

**Comment by joescii** [comment]
This issue is resolved with 0.9.3. [Release notes](http://notes.implicit.ly/post/143888869069/lift-ng-093). 

Thanks for the report, Dave!

**Comment by davenatx** [comment]
Thank you for taking care of this Joe!
