### ISSUE TITLE
Watch on scope.obj not triggering when using comet

### ISSUE THREAD

**Issue by colinbes** [joescii/lift-ng#17]
I am using liftweb 3.0 lift-ng_3.0_2.11 ver  0.9.3 and messing around with comet functionality.

I have lift-ng installed and working but my watch on object change is not triggering. I have also tried deep watch.

My controller code is
```
...
$scope.myObj = {name:""}

$scope.$watch(function(){
	return $scope.myObj //have also tried return $scope.myObj.name
}, function(e, obj) {
	console.log("got ", e, obj) //only see this first time round when controller is instantiated
}, true);
```

My Comet class is:
```
case class Data(name: String)

class CometExample extends AngularActor {
  var counter = 0;
  Schedule.schedule(this, ("assign", Data(s"abc-$counter")), 2.second)

  override def lowPriority = {
    case ("assign", obj: AnyRef)    => {
      scope.assign("myObj", obj)
      counter += 1
      Schedule.schedule(this, ("assign", Data(s"abc-$counter")), 2.second)
    }
  }
}
```

HTML snippet is:
```
<div data-lift="comet?type=CometExample"></div>
myObj {{myObj}}
```

Every time the scheduler triggers I do see the HTML view updating display (abc-0, abc-1, ...) only see watch triggered once, and not every two seconds.

Ideas?

**Comment by joescii** [comment]
At a glance I don't see anything obviously wrong here. What version of angular are you using? And have you tried a similar change every 2 seconds but with client-side code only? 

Also, have you tried giving the name of the field as a string, rather than a function that returns the value? i.e.

```
$scope.$watch('myObj', function(e, obj) {
	console.log("got ", e, obj)
}, true);
```

My knee-jerk reaction is that this is an angular problem considering the HTML is changing, or perhaps

**Comment by colinbes** [comment]
Weirdly I am unable to get the above snippets to fail. Not sure if it was a caching issue as I am sure I cleared cache, but all is working as expected.

As always, thanks for your response and ideas.
