### ISSUE TITLE
$on($destroy,..) question

### ISSUE THREAD

**Issue by colinbes** [joescii/lift-ng#18]
I have noticed that when switching pages (user clicking on different page, lift instantiating new snippet) that angular controller's $destroy event doesn't get triggered so am unable to do any client side cleanup.

I am assuming that this is due to (assume) DOM replacement but wanted to get your take on this and I am concerned about potential memory leaks.

Thanks
Colin

**Comment by joescii** [comment]
If I understand you correctly, you are talking about a page load from the server. In that case, I don't know I would expect any clean up code to be executed, much less necessary. A browser that would allow a page to use memory when the page is no longer in view wouldn't be a very good browser.

**Comment by colinbes** [comment]
That's my thinking as well and just wanted to bounce it off someone in the know.

Thanks
