### ISSUE TITLE
Nicely Done

### ISSUE THREAD

**Issue by colinbes** [joescii/lift-ng#38]
I am have updated to 0.11.0 and upgrade was painless and for a large project took me about an hour to complete. I have to admit that over the course of last year I have been updating various calls knowing change is coming so it also helped.

Not having NgModel dependency has cleaned up code nicely and I really like this update.

Congrats!

**Comment by joescii** [comment]
Thanks Colin! It was big effort prompted by @Bhashit's code prowess and frustration with me work. :)
