### ISSUE TITLE
defParamToFutureAny failing with slow connection

### ISSUE THREAD

**Issue by colinbes** [joescii/lift-ng#39]
I have this problem with both 0.10.x and 0.11.0 (haven't tried with any other versions) where future service response (nor error) is not received in controller code when simulating slow network using chrome browser.

in lift snippet using:
```
.defParamToFutureAny("getTickets", (fromDate:FromDate) => IssueService.getTickets(sessionUserId, fromDate))
```
where getTickets is defined as:
```
def getTickets(userId: FetcherObjectId, page: FromDate): Future[JValue] = { ... }
```

and in corresponding controller code calling service function:
```
postsService.getTickets(page).then(function(response) {
  console.log("response getOverview", response)
  ...
}, function(error) {
console.log("error", error)
})
```

If I instead wait for future completion using Await.result(getTickets) and return Box[JValue] as opposed to Future[JValue] then response is received and processed.

With no network throttling is works perfectly well.

I don't see any timeout messages or other errors.

Suggestions appreciated. Unless there is valid reason for not using defParamToFutureAny and rather defParamToAny I'd prefer working with futures.

Thanks
Colin

**Comment by joescii** [comment]
Interesting find, Colin! I'll take a look hopefully soon. As an FYI in case you have time to do more investigating: lift-ng's future support is implemented via comet pushes. So this could be more about the behavior of comets under your slow network simulation.

**Comment by colinbes** [comment]
Thanks Joe, my suspect is comet. Got a little more else to do to demo system and then I will experiment for more. For now I am wrapping future response in Await so I can continue.

Always happy to help where I can. Sad thing this is a large project so hard to share code but will most probably create smaller project to mess around with.

**Comment by joescii** [comment]
Definitely set up a repo for a small Lift project to reproduce problems. That's what I made my `lift-help` repo for. I use it _all_ the time.

**Comment by colinbes** [comment]
I have created small repo demonstrating the problem. Haven't had a chance to dig in yet but demo shows the issue and demo's future call, sync call and delayed sync call.

https://github.com/colinbes/lift-3

**Comment by colinbes** [comment]
Haven't had a chance to dig deeper into this yet, hopefully soon as project is nearing an end and I'd like to remove my Await wrappers.

**Comment by colinbes** [comment]
Was wondering if you've had a chance to look into this yet?

**Comment by joescii** [comment]
I believe I recently discovered this same issue and fixed it. I ran your project against lift-ng 0.12.0-RC3 and was no longer able to reproduce the problem. Note that you will need to import `AngularExecutionContext._` for your lift-ng service in place of the usual `ExecutionContext.global` import.

**Comment by colinbes** [comment]
Sweet, I will give it a test drive!

**Comment by colinbes** [comment]
I confirm that changes to 0.12.0-RC3 work!
