### ISSUE TITLE
net.liftmodules.ng.Angular.ajaxError RetryExceeded

### ISSUE THREAD

**Issue by colinbes** [joescii/lift-ng#45]
We have sporadic reports of users seeing _net.liftmodules.ng.Angular.ajaxError RetryExceeded_ error message. We have moved our database onto separate server so am suspecting it may be related to this.

I assume this message stems from lift-ng dependency and am looking to see what options I have for overriding settings to give more leeway until we figure it out.

I see settings for "retryAjaxInOrder=boolean" (which I don't set) but don't see settings for retry count. I do see mention made of _net.liftmodules.ng.AngularActor.retryInterval_ which can be set in props file - Is this related to interval behind ajaxError RetryExceeded (at least the interval component)?

Is there a similar setting for number of retries?

Are these driven at all by Lift's:

- LiftRules.ajaxPostTimeout = ajaxTimeout
- LiftRules.ajaxRetryCount = Full(ajaxRetry)

Any other suggestions appreciated.

**Comment by colinbes** [comment]
Apologies for bumping this as I know you're slammed but if you could give me slightest nudge in right direction I will carry on.

**Comment by joescii** [comment]
Sure, sorry for the delay. You're looking at the right settings in `LiftRules`. The `ajaxErrorRetryExceeded` message is indeed in lift-ng code, but is printed whenever Lift finally gives up on the ajax request and calls the failure handler.

**Comment by colinbes** [comment]
Thanks @joescii

**Comment by colinbes** [comment]
Closing
