### ISSUE TITLE
AngularJS versions

### ISSUE THREAD

**Issue by colinbes** [joescii/lift-ng#47]
Presently I am using AngularJs 1.6.x with lift-ng_3.1_2.11 version 0.12.1 and am considering upgrading to latest Angular 1.7x version and was wondering how AngularJs versioning and lift-ng relate - how dependent lift-ng is on specific angular versions?

Apologies if I missed seeing this but I didn't see mention of AngularJS versions per lift-ng version

**Comment by joescii** [comment]
Before this morning, I had not tried Angular 1.7.x with lift-ng, nor am I aware of anyone else who is. I updated the version in `test-project` to 1.7.5 and ran the full test suite. All tests pass! It should be good to go. I'll update the repo when I get some more time.

**Comment by colinbes** [comment]
Thanks Joe much appreciate you running the tests.

**Comment by colinbes** [comment]
Closing
