### ISSUE TITLE
lift 3.0-snapshot ajax_request, lift_page in liftproxy.js

### ISSUE THREAD

**Issue by ekzeb** [joescii/lift-ng#6]
lift-3.0-snapshot scala 2.11
liftproxy.js:46
return $http.post(net_liftmodules_ng.contextPath + '/ajax_request/' + lift_page + '/', req, { lines... })
the post request returns 404

May be i’m wrong, but lift-3.0-SNAPSHOT has no '/ajax_request/‘ path and lift_page global var any more, at least, i could’t find these searching the code 

PS
To make it work, i replace /module/liftproxy.js with changed version
my_liftproxy.js:46
return $http.post(net_liftmodules_ng.contextPath || + '/ajax/' + window.lift.getPageId() + '/', req, { lines... })
and then in template
net_liftmodules_ng.contextPath = window.lift_settings.liftPath

**Comment by tek** [comment]
does this apply to 2.6 as well meanwhile? `lift_page` is undefined in my app and manually setting it to an arbitrary value leads to successful service calls.

**Comment by joescii** [comment]
I'm surprised you're having issues with 2.6 as this was an issue specific to 3.0.  We're using the latest lift-ng with 2.6 at my day job without problems.  Can you create a minimal example project on github which exhibits the troublesome behavior?

**Comment by tek** [comment]
Will do!

**Comment by tek** [comment]
I'm totally lost. Could you explain to me how the `lift_page` variable is set? I can't find it anywhere in the lift source.

**Comment by joescii** [comment]
Are you looking in the 2.6 code? It has been removed in 3.0.

**Comment by tek** [comment]
thanks, seems I'm too incompetent for github search ;) Now after using the 2.6.2-release tag from source as an sbt dep and tweaking the build definition to work, I've easily identified the culprit: I've been embedding my pages recursively, i.e. one template for the header only and one for common body html, which seems to lead lift into treating the page as not having head and body, thus not injecting the whole ajax shebang.
Anyway, obviously not a lift-ng problem. Now my ng future actor finally works like a charm! :) Btw, very grateful for your work, I can't imagine a reason to use any other solution for a webapp.
Now to find out whether recursive template embedding with header is supported at all.

**Comment by joescii** [comment]
awesome, glad you figured it out! Bring your questions about recursive embedding to the [Google Group](https://groups.google.com/forum/#!forum/liftweb) and I'm sure you'll get some good help.

**Comment by tek** [comment]
spoke too soon, seems it was a fluke that it worked. I now noticed that the html being processed in LiftMerge, where the ajax code is injected, is wrapped in an additional `<html>`, which confuses lift. Could this be caused by lift-ng?
Completely avoiding `surround` seems to prevent the garbage tag for now.

**Comment by joescii** [comment]
I would expect that to be a general Lift problem/question since lift-ng really is just a wrapper around ajax and comet.
